package com.example.requiemrestservice.controller;

import com.example.requiemrestservice.model.MyUser;
import com.example.requiemrestservice.service.MyUserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/user")
public class UserController {
    @Autowired // This means to get the bean called userRepository. Which is auto-generated by Spring, we will use it to handle the data
    private MyUserService myUserService;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String username, @RequestParam String email) {

        MyUser n = new MyUser();
        n.setUsername(username);
        n.setEmail(email);
        myUserService.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<MyUser> getAllUsers() {
        // This returns a JSON or XML with the users
        return myUserService.getAll();
    }

    @GetMapping(path="/test")
    public String test() {
        return "Hello, ALL DONE";
    }
}
